print('-' * 35)
print('Tugas SISOP Kelas-B')
print('-' * 35)
print('Nama: Rakha Rizky Mahendra')
print('NPM  : 20183010013')
print('-' * 35)
print(' notes: ')
print('-' * 35)
print('Halo dunia!')
print('Ini adalah skrip Bash pertamaku di Linux')
